### ISSUE TITLE
address use error

### ISSUE THREAD

**Issue by sappi13** [0ang3el/aem-hacker#11]
Could you point out why I am getting this error, as I restarted the machine and also killed required process?

`Traceback (most recent call last):
  File "aem_hacker.py", line 1532, in <module>
    main()
  File "aem_hacker.py", line 1513, in main
    httpd = run_detector(args.port)
  File "aem_hacker.py", line 1475, in run_detector
    httpd = HTTPServer(('', port), handler)
  File "/usr/lib/python3.5/socketserver.py", line 441, in __init__
    self.server_activate()
  File "/usr/lib/python3.5/socketserver.py", line 463, in server_activate
    self.socket.listen(self.request_queue_size)
OSError: [Errno 98] Address already in use`

**Comment by anixzh** [comment]
I'm getting the Exact same Error.

**Comment by xElkomy** [comment]
i have same Error

**Comment by ByQwert** [comment]
Hello, 

By default _aem_hacker.py_ uses **80** port for SSRF detection.
In most cases it is already binded by web server.

Please, update to the latest version and set other port via **--port** flag.

**Comment by hridoua** [comment]
any solution of this error?

**Comment by xElkomy** [comment]
> any solution of this error?

Please, update to the latest version and set other port via --port flag.
