### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by s41n1k** [0ang3el/aem-hacker#28]
While I run this cmd: `python3 aem_hacker.py -u https://site.com --host 100.000.00.000`
The error comes.

```
Traceback (most recent call last):
  File "aem_hacker.py", line 1676, in <module>
    main()
  File "aem_hacker.py", line 1648, in main
    httpd = run_detector(args.port)
  File "aem_hacker.py", line 1605, in run_detector
    httpd = HTTPServer(('', port), handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

Solutions?
Thank you

**Comment by s41n1k** [comment]
I kill every service on Python, but still, an error comes.

**Comment by dpkeesling** [comment]
I had the same issue. It was because I had a webserver running that was bound to port 80. I ran `systemctl stop apache2` and that resolved the issue.
